export const todo = [{
    "id": "7e39dea6-e65a-06ad-17f4-4b252b94a8fe",
    "title": "test00000",
    "category": "普通事项",
    "remindDate": "2019-06-28T07:34:00.000Z",
    "times": 0,
    "status": 0,
    "checked": false,
    "isShow": true,
    "isRecover": false,
    "editVisible": false
}, {
    "title": "点击选择框完成任务",
    "category": "普通事项",
    "remindDate": "2019-06-22T10:32:00.000Z",
    "times": "每天",
    "status": 1,
    "checked": true,
    "isShow": true,
    "isRecover": false,
    "editVisible": false
}, {
    "title": "关闭弹层后内容重置",
    "category": "普通事项",
    "remindDate": "2019-06-22T10:32:00.000Z",
    "times": "每小时",
    "status": 1,
    "checked": true,
    "isShow": true,
    "isRecover": false,
    "editVisible": false
}, {
    "title": "即时搜索功能",
    "category": "普通事项",
    "remindDate": "2019-06-22T10:32:00.000Z",
    "times": "每小时",
    "status": 1,
    "checked": true,
    "isShow": true,
    "isRecover": false,
    "editVisible": false
}, {
    "title": "本地存储功能",
    "category": "重要事项",
    "remindDate": "2019-06-22T10:32:00.000Z",
    "times": "每小时",
    "status": 1,
    "checked": true,
    "isShow": true,
    "isRecover": false,
    "editVisible": false
}, {
    "title": "筛选功能",
    "category": "普通事项",
    "remindDate": "2019-06-22T10:32:00.000Z",
    "times": "每天",
    "status": 1,
    "checked": true,
    "isShow": true,
    "isRecover": false,
    "editVisible": false
}, {
    "title": "test",
    "category": "",
    "remindDate": "2019-06-22T10:32:00.000Z",
    "times": "每天",
    "status": 1,
    "checked": true,
    "isShow": true,
    "isRecover": false,
    "editVisible": false
}, {
    "title": "test",
    "category": "",
    "remindDate": "2019-06-22T10:32:00.000Z",
    "times": "每天",
    "status": 1,
    "checked": true,
    "isShow": true,
    "isRecover": false,
    "editVisible": false
}]

export const menu = [{
    name: "全部",
    num: 0,
    icon: "icon-shoucang",
    type: "all",
    checked: false
}, {
    name: "废稿箱",
    num: 0,
    icon: "icon-shanchu",
    type: "recover",
    checked: false
}, {
    name: "重要事项",
    num: 0,
    icon: "icon-wenjian",
    type: "taskbox",
    checked: false
}, {
    name: "普通事项",
    num: 0,
    icon: "icon-wenjian",
    type: "taskbox",
    checked: false
}]